/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as GuestRouteImport } from './routes/_guest'
import { Route as FreelanceRouteImport } from './routes/_freelance'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GuestSignUpRouteImport } from './routes/_guest/sign-up'
import { Route as GuestSignInRouteImport } from './routes/_guest/sign-in'
import { Route as FreelanceFreelanceRouteImport } from './routes/_freelance/freelance'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedFreelanceSignUpRouteImport } from './routes/_authenticated/freelance-sign-up'
import { Route as AuthenticatedEditProfileRouteImport } from './routes/_authenticated/edit-profile'
import { Route as AdminAdminRouteImport } from './routes/_admin/admin'
import { Route as AuthenticatedServiceIndexRouteImport } from './routes/_authenticated/service/index'
import { Route as AuthenticatedServiceIdRouteImport } from './routes/_authenticated/service/$id'

const GuestRoute = GuestRouteImport.update({
  id: '/_guest',
  getParentRoute: () => rootRouteImport,
} as any)
const FreelanceRoute = FreelanceRouteImport.update({
  id: '/_freelance',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuestSignUpRoute = GuestSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => GuestRoute,
} as any)
const GuestSignInRoute = GuestSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => GuestRoute,
} as any)
const FreelanceFreelanceRoute = FreelanceFreelanceRouteImport.update({
  id: '/freelance',
  path: '/freelance',
  getParentRoute: () => FreelanceRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFreelanceSignUpRoute =
  AuthenticatedFreelanceSignUpRouteImport.update({
    id: '/freelance-sign-up',
    path: '/freelance-sign-up',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedEditProfileRoute =
  AuthenticatedEditProfileRouteImport.update({
    id: '/edit-profile',
    path: '/edit-profile',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AdminAdminRoute = AdminAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AdminRoute,
} as any)
const AuthenticatedServiceIndexRoute =
  AuthenticatedServiceIndexRouteImport.update({
    id: '/service/',
    path: '/service/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedServiceIdRoute = AuthenticatedServiceIdRouteImport.update({
  id: '/service/$id',
  path: '/service/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminAdminRoute
  '/edit-profile': typeof AuthenticatedEditProfileRoute
  '/freelance-sign-up': typeof AuthenticatedFreelanceSignUpRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/freelance': typeof FreelanceFreelanceRoute
  '/sign-in': typeof GuestSignInRoute
  '/sign-up': typeof GuestSignUpRoute
  '/service/$id': typeof AuthenticatedServiceIdRoute
  '/service/': typeof AuthenticatedServiceIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminAdminRoute
  '/edit-profile': typeof AuthenticatedEditProfileRoute
  '/freelance-sign-up': typeof AuthenticatedFreelanceSignUpRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/freelance': typeof FreelanceFreelanceRoute
  '/sign-in': typeof GuestSignInRoute
  '/sign-up': typeof GuestSignUpRoute
  '/service/$id': typeof AuthenticatedServiceIdRoute
  '/service': typeof AuthenticatedServiceIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_admin': typeof AdminRouteWithChildren
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_freelance': typeof FreelanceRouteWithChildren
  '/_guest': typeof GuestRouteWithChildren
  '/_admin/admin': typeof AdminAdminRoute
  '/_authenticated/edit-profile': typeof AuthenticatedEditProfileRoute
  '/_authenticated/freelance-sign-up': typeof AuthenticatedFreelanceSignUpRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_freelance/freelance': typeof FreelanceFreelanceRoute
  '/_guest/sign-in': typeof GuestSignInRoute
  '/_guest/sign-up': typeof GuestSignUpRoute
  '/_authenticated/service/$id': typeof AuthenticatedServiceIdRoute
  '/_authenticated/service/': typeof AuthenticatedServiceIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/edit-profile'
    | '/freelance-sign-up'
    | '/profile'
    | '/freelance'
    | '/sign-in'
    | '/sign-up'
    | '/service/$id'
    | '/service/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/edit-profile'
    | '/freelance-sign-up'
    | '/profile'
    | '/freelance'
    | '/sign-in'
    | '/sign-up'
    | '/service/$id'
    | '/service'
  id:
    | '__root__'
    | '/'
    | '/_admin'
    | '/_authenticated'
    | '/_freelance'
    | '/_guest'
    | '/_admin/admin'
    | '/_authenticated/edit-profile'
    | '/_authenticated/freelance-sign-up'
    | '/_authenticated/profile'
    | '/_freelance/freelance'
    | '/_guest/sign-in'
    | '/_guest/sign-up'
    | '/_authenticated/service/$id'
    | '/_authenticated/service/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  FreelanceRoute: typeof FreelanceRouteWithChildren
  GuestRoute: typeof GuestRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_guest': {
      id: '/_guest'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof GuestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_freelance': {
      id: '/_freelance'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof FreelanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_guest/sign-up': {
      id: '/_guest/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof GuestSignUpRouteImport
      parentRoute: typeof GuestRoute
    }
    '/_guest/sign-in': {
      id: '/_guest/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof GuestSignInRouteImport
      parentRoute: typeof GuestRoute
    }
    '/_freelance/freelance': {
      id: '/_freelance/freelance'
      path: '/freelance'
      fullPath: '/freelance'
      preLoaderRoute: typeof FreelanceFreelanceRouteImport
      parentRoute: typeof FreelanceRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/freelance-sign-up': {
      id: '/_authenticated/freelance-sign-up'
      path: '/freelance-sign-up'
      fullPath: '/freelance-sign-up'
      preLoaderRoute: typeof AuthenticatedFreelanceSignUpRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/edit-profile': {
      id: '/_authenticated/edit-profile'
      path: '/edit-profile'
      fullPath: '/edit-profile'
      preLoaderRoute: typeof AuthenticatedEditProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_admin/admin': {
      id: '/_admin/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminAdminRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_authenticated/service/': {
      id: '/_authenticated/service/'
      path: '/service'
      fullPath: '/service/'
      preLoaderRoute: typeof AuthenticatedServiceIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/service/$id': {
      id: '/_authenticated/service/$id'
      path: '/service/$id'
      fullPath: '/service/$id'
      preLoaderRoute: typeof AuthenticatedServiceIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAdminRoute: typeof AdminAdminRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAdminRoute: AdminAdminRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedEditProfileRoute: typeof AuthenticatedEditProfileRoute
  AuthenticatedFreelanceSignUpRoute: typeof AuthenticatedFreelanceSignUpRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedServiceIdRoute: typeof AuthenticatedServiceIdRoute
  AuthenticatedServiceIndexRoute: typeof AuthenticatedServiceIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedEditProfileRoute: AuthenticatedEditProfileRoute,
  AuthenticatedFreelanceSignUpRoute: AuthenticatedFreelanceSignUpRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedServiceIdRoute: AuthenticatedServiceIdRoute,
  AuthenticatedServiceIndexRoute: AuthenticatedServiceIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface FreelanceRouteChildren {
  FreelanceFreelanceRoute: typeof FreelanceFreelanceRoute
}

const FreelanceRouteChildren: FreelanceRouteChildren = {
  FreelanceFreelanceRoute: FreelanceFreelanceRoute,
}

const FreelanceRouteWithChildren = FreelanceRoute._addFileChildren(
  FreelanceRouteChildren,
)

interface GuestRouteChildren {
  GuestSignInRoute: typeof GuestSignInRoute
  GuestSignUpRoute: typeof GuestSignUpRoute
}

const GuestRouteChildren: GuestRouteChildren = {
  GuestSignInRoute: GuestSignInRoute,
  GuestSignUpRoute: GuestSignUpRoute,
}

const GuestRouteWithChildren = GuestRoute._addFileChildren(GuestRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  FreelanceRoute: FreelanceRouteWithChildren,
  GuestRoute: GuestRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
